# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0003_auto_20170922_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_author', to='belt_reviewer.Book'),
        ),
    ]
