# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0005_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='book',
            name='reviewed_users',
            field=models.ManyToManyField(related_name='reviewed_books', to='belt_reviewer.User'),
        ),
    ]
